# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='cut',
        ),
        migrations.AddField(
            model_name='article',
            name='rest_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
