# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20160904_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cut',
            new_name='cut_md',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='rest_text',
            new_name='rest_text_md',
        ),
        migrations.AddField(
            model_name='article',
            name='cut_html',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='rest_text_html',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
    ]
